---
title: sara hendren
timezone: America/New_York
collections:
  projects-lab:
    title: Projects + Lab
    output: true
  abler-archive:
    title: Abler/Archive
    output: true
  posts:
    title: Reading/Notes
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: abler-archive
  values:
    parent: "/abler-archive/"
    image: http://placehold.it/400x300
    image-caption: IMAGE CAPTION
    date-display: DISPLAY DATE
    layout: abler
- scope:
    path: ''
    type: projects-lab
  values:
    parent: "/projects-lab/"
    image: http://placehold.it/400x300
    image-caption: IMAGE CAPTION
    date-display: DISPLAY DATE
    subtitle: SUBTITLE
    layout: project
- scope:
    path: ''
    type: posts
  values:
    parent: "/reading-notes/"
    layout: reading-note

permalink: pretty
plugins:
- jekyll-redirect-from
- jekyll-feed
- jekyll-assets
author: Sara Hendren
exclude:
- gulpfile.js
include:
- _redirects
assets:
  prefix: "/assets"
  digest: true
  assets:
  - "*.png"
  - "*.jpg"
  sources:
  - _uploads
