---
title: sara hendren
timezone: America/New_York
collections:
  projects:
    title: Projects
    output: true
  posts:
    title: Reading Notes
    output: true
  talks-essays:
    title: Talks + Essays
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: projects
  values:
    parent: "/projects/"
    image: http://placehold.it/400x300
    image-caption: IMAGE CAPTION
    date-display: DISPLAY DATE
    subtitle: SUBTITLE
    layout: project
- scope:
    path: ''
    type: posts
  values:
    parent: "/reading-notes/"
    layout: page
- scope:
    path: ''
    type: talks-essays
  values:
    parent: "/talks-essays/"
    image: http://placehold.it/400x300
    image-caption: IMAGE CAPTION
    date-display: DISPLAY DATE
    subtitle: SUBTITLE
    layout: page
permalink: pretty
plugins:
- jekyll-redirect-from
- jekyll-feed
- jekyll-assets
author:
  twitter: ablerism
exclude:
- node_modules
- gulpfile.js
include:
- _redirects
assets:
  prefix: "/assets"
  digest: true
  assets:
  - "*.png"
  - "*.jpg"
  sources:
  - _uploads
