---
title: Sara Hendren
url: http://sarahendren.siteleaf.net
timezone: UTC
collections:
  projects:
    title: Projects
    output: true
  reading-notes:
    title: Reading Notes
    output: true
  talks-plus-essays:
    title: Talks + Essays
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
